# Aula 1 - Aprendizagem Supervisionada
### Base de dados: Github do Curso e no https://www.kaggle.com/datasets/uciml/red-wine-quality-cortez-et-al-2009/data

  O conjunto de dados se refere a uma base que avalia a qualidade das sementes para a produção vinícola, 
a partir das diferentes variedades de sementes de trigo.

In [3]:
!pip install pandas numpy
!pip install -U scikit-learn

In [4]:
import pandas as pd
import numpy as np
# from sklearn.modulo import Arquivo

In [5]:
data = pd.read_csv('base_dados/winequality-red.csv')
data

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
1594            6.2             0.600         0.08             2.0      0.090   
1595            5.9             0.550         0.10             2.2      0.062   
1596            6.3             0.510         0.13             2.3      0.076   
1597            5.9             0.645         0.12             2.0      0.075   
1598            6.0             0.310         0.47             3.6      0.067   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
3                    17.0                  60.0  0.99800  3.16       0.58   
4                    11.0                  34.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
1594                 32.0                  44.0  0.99490  3.45       0.58   
1595                 39.0                  51.0  0.99512  3.52       0.76   
1596                 29.0                  40.0  0.99574  3.42       0.75   
1597                 32.0                  44.0  0.99547  3.57       0.71   
1598                 18.0                  42.0  0.99549  3.39       0.66   

      alcohol  quality  
0         9.4        5  
1         9.8        5  
2         9.8        5  
3         9.8        6  
4         9.4        5  
...       ...      ...  
1594     10.5        5  
1595     11.2        6  
1596     11.0        6  
1597     10.2        5  
1598     11.0        6  

[1599 rows x 12 columns]

In [6]:
data.columns

Index(['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol', 'quality'],
      dtype='object')

In [7]:
data.quality.value_counts()

quality
5    681
6    638
7    199
4     53
8     18
3     10
Name: count, dtype: int64

In [9]:
data['Class'] = np.where(data.quality >=6, 1, 0)
data.Class.value_counts()

Class
1    855
0    744
Name: count, dtype: int64

In [10]:
data.shape

(1599, 13)

In [11]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1599 entries, 0 to 1598
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   fixed acidity         1599 non-null   float64
 1   volatile acidity      1599 non-null   float64
 2   citric acid           1599 non-null   float64
 3   residual sugar        1599 non-null   float64
 4   chlorides             1599 non-null   float64
 5   free sulfur dioxide   1599 non-null   float64
 6   total sulfur dioxide  1599 non-null   float64
 7   density               1599 non-null   float64
 8   pH                    1599 non-null   float64
 9   sulphates             1599 non-null   float64
 10  alcohol               1599 non-null   float64
 11  quality               1599 non-null   int64  
 12  Class                 1599 non-null   int64  
dtypes: float64(11), int64(2)
memory usage: 162.5 KB


In [12]:
data.drop(columns=['quality'], axis=1, inplace=True)
data

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
1594            6.2             0.600         0.08             2.0      0.090   
1595            5.9             0.550         0.10             2.2      0.062   
1596            6.3             0.510         0.13             2.3      0.076   
1597            5.9             0.645         0.12             2.0      0.075   
1598            6.0             0.310         0.47             3.6      0.067   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
3                    17.0                  60.0  0.99800  3.16       0.58   
4                    11.0                  34.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
1594                 32.0                  44.0  0.99490  3.45       0.58   
1595                 39.0                  51.0  0.99512  3.52       0.76   
1596                 29.0                  40.0  0.99574  3.42       0.75   
1597                 32.0                  44.0  0.99547  3.57       0.71   
1598                 18.0                  42.0  0.99549  3.39       0.66   

      alcohol  Class  
0         9.4      0  
1         9.8      0  
2         9.8      0  
3         9.8      1  
4         9.4      0  
...       ...    ...  
1594     10.5      0  
1595     11.2      1  
1596     11.0      1  
1597     10.2      0  
1598     11.0      1  

[1599 rows x 12 columns]

------

In [ ]:
# treino e teste

In [14]:
X = data.drop(columns=['Class'], axis=1)
y = data['Class']

In [15]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42, stratify=y)

-------
## Machine Learning
### SVM

In [16]:
from sklearn.svm import SVC

clf_svm = SVC()
clf_svm.fit(X_train, y_train)

SVC()

In [18]:
X_test

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
1101            7.4              0.49         0.27             2.1      0.071   
788            10.0              0.56         0.24             2.2      0.079   
8               7.8              0.58         0.02             2.0      0.073   
674            10.8              0.40         0.41             2.2      0.084   
1290            7.6              0.74         0.00             1.9      0.100   
...             ...               ...          ...             ...        ...   
1075            9.1              0.25         0.34             2.0      0.071   
545             9.1              0.47         0.49             2.6      0.094   
1240            7.5              0.61         0.20             1.7      0.076   
1237            7.1              0.75         0.01             2.2      0.059   
290             8.7              0.52         0.09             2.5      0.091   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
1101                 14.0                  25.0  0.99388  3.35       0.63   
788                  19.0                  58.0  0.99910  3.18       0.56   
8                     9.0                  18.0  0.99680  3.36       0.57   
674                   7.0                  17.0  0.99840  3.08       0.67   
1290                  6.0                  12.0  0.99521  3.36       0.59   
...                   ...                   ...      ...   ...        ...   
1075                 45.0                  67.0  0.99769  3.44       0.86   
545                  38.0                 106.0  0.99820  3.08       0.59   
1240                 36.0                  60.0  0.99494  3.10       0.40   
1237                 11.0                  18.0  0.99242  3.39       0.40   
290                  20.0                  49.0  0.99760  3.34       0.86   

      alcohol  
1101     12.0  
788      10.1  
8         9.5  
674       9.3  
1290     11.0  
...       ...  
1075     10.2  
545       9.1  
1240      9.3  
1237     12.8  
290      10.6  

[480 rows x 11 columns]

In [19]:
y_pred = clf_svm.predict(X_test)

In [20]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.6229166666666667

In [21]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[ 84, 139],
       [ 42, 215]])

In [115]:
# make_pipeline
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler

clf_svm2 = make_pipeline(StandardScaler(), SVC())
clf_svm2.fit(X_train, y_train)

Pipeline(steps=[('standardscaler', StandardScaler()), ('svc', SVC())])

In [116]:
y_pred = clf_svm2.predict(X_test)

In [117]:
accuracy_score(y_test, y_pred)

0.7458333333333333

In [118]:
confusion_matrix(y_test, y_pred)

array([[167,  56],
       [ 66, 191]])

---------
### Regressão Logística

In [22]:
from sklearn.linear_model import LogisticRegression

clf_lr = LogisticRegression()
clf_lr.fit(X_train, y_train)

/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [24]:
y_pred = clf_lr.predict(X_test)

In [25]:
accuracy_score(y_test, y_pred)

0.7458333333333333

In [26]:
confusion_matrix(y_test, y_pred)

array([[163,  60],
       [ 62, 195]])

-------
### Árvores de Decisão

In [72]:
from sklearn.tree import DecisionTreeClassifier

In [73]:
clf_tree = DecisionTreeClassifier()
clf_tree.fit(X_train, y_train)

DecisionTreeClassifier()

In [74]:
y_pred = clf_tree.predict(X_test)

In [75]:
accuracy_score(y_test, y_pred)

0.7645833333333333

In [76]:
confusion_matrix(y_test, y_pred)

array([[161,  62],
       [ 51, 206]])

In [77]:
# import matplotlib.pyplot as plt
# from sklearn.tree import plot_tree

In [78]:
# plt.figure(figsize=(12, 8))
# plot_tree(clf_tree, feature_names=X_train.columns, class_names=['Ruim', 'Ótima'], filled=True, rounded=True)
# plt.show()

--------
### Random Forest

In [80]:
from sklearn.ensemble import RandomForestClassifier

In [97]:
clf_rf = RandomForestClassifier(n_estimators=30).fit(X_train, y_train)

In [98]:
y_pred = clf_rf.predict(X_test)

In [99]:
accuracy_score(y_test, y_pred)

0.775

In [100]:
confusion_matrix(y_test, y_pred)

array([[165,  58],
       [ 50, 207]])

-------
### Knn Classifier

In [108]:
from sklearn.neighbors import KNeighborsClassifier

In [109]:
clf_knn = KNeighborsClassifier(n_neighbors=10)
clf_knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=10)

In [110]:
y_pred = clf_knn.predict(X_test)

accuracy_score(y_test, y_pred)

0.6458333333333334

In [111]:
confusion_matrix(y_test, y_pred)

array([[160,  63],
       [107, 150]])

In [119]:
# make_pipeline
clf_knn2 = make_pipeline(StandardScaler(), KNeighborsClassifier(n_neighbors=10))
clf_knn2.fit(X_train, y_train)

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('kneighborsclassifier', KNeighborsClassifier(n_neighbors=10))])

In [120]:
y_pred = clf_knn2.predict(X_test)

accuracy_score(y_test, y_pred)

0.7375

In [121]:
confusion_matrix(y_test, y_pred)

array([[168,  55],
       [ 71, 186]])

----------

In [112]:
data

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
1594            6.2             0.600         0.08             2.0      0.090   
1595            5.9             0.550         0.10             2.2      0.062   
1596            6.3             0.510         0.13             2.3      0.076   
1597            5.9             0.645         0.12             2.0      0.075   
1598            6.0             0.310         0.47             3.6      0.067   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
3                    17.0                  60.0  0.99800  3.16       0.58   
4                    11.0                  34.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
1594                 32.0                  44.0  0.99490  3.45       0.58   
1595                 39.0                  51.0  0.99512  3.52       0.76   
1596                 29.0                  40.0  0.99574  3.42       0.75   
1597                 32.0                  44.0  0.99547  3.57       0.71   
1598                 18.0                  42.0  0.99549  3.39       0.66   

      alcohol  Class  
0         9.4      0  
1         9.8      0  
2         9.8      0  
3         9.8      1  
4         9.4      0  
...       ...    ...  
1594     10.5      0  
1595     11.2      1  
1596     11.0      1  
1597     10.2      0  
1598     11.0      1  

[1599 rows x 12 columns]

In [113]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
data.loc[:,:] = scaler.fit_transform(data)

In [114]:
data

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0         -0.528360          0.961877    -1.391472       -0.453218  -0.243707   
1         -0.298547          1.967442    -1.391472        0.043416   0.223875   
2         -0.298547          1.297065    -1.186070       -0.169427   0.096353   
3          1.654856         -1.384443     1.484154       -0.453218  -0.264960   
4         -0.528360          0.961877    -1.391472       -0.453218  -0.243707   
...             ...               ...          ...             ...        ...   
1594      -1.217796          0.403229    -0.980669       -0.382271   0.053845   
1595      -1.390155          0.123905    -0.877968       -0.240375  -0.541259   
1596      -1.160343         -0.099554    -0.723916       -0.169427  -0.243707   
1597      -1.390155          0.654620    -0.775267       -0.382271  -0.264960   
1598      -1.332702         -1.216849     1.021999        0.752894  -0.434990   

      free sulfur dioxide  total sulfur dioxide   density        pH  \
0               -0.466193             -0.379133  0.558274  1.288643   
1                0.872638              0.624363  0.028261 -0.719933   
2               -0.083669              0.229047  0.134264 -0.331177   
3                0.107592              0.411500  0.664277 -0.979104   
4               -0.466193             -0.379133  0.558274  1.288643   
...                   ...                   ...       ...       ...   
1594             1.542054             -0.075043 -0.978765  0.899886   
1595             2.211469              0.137820 -0.862162  1.353436   
1596             1.255161             -0.196679 -0.533554  0.705508   
1597             1.542054             -0.075043 -0.676657  1.677400   
1598             0.203223             -0.135861 -0.666057  0.511130   

      sulphates   alcohol     Class  
0     -0.579207 -0.960246 -1.072004  
1      0.128950 -0.584777 -1.072004  
2     -0.048089 -0.584777 -1.072004  
3     -0.461180 -0.584777  0.932832  
4     -0.579207 -0.960246 -1.072004  
...         ...       ...       ...  
1594  -0.461180  0.072294 -1.072004  
1595   0.601055  0.729364  0.932832  
1596   0.542042  0.541630  0.932832  
1597   0.305990 -0.209308 -1.072004  
1598   0.010924  0.541630  0.932832  

[1599 rows x 12 columns]

In [ ]:
X = data.drop(columns=['Class'], axis=1)
y = data['Class']